// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (creator_id, title, description, category, location_name, location, start_time, end_time, max_participants, status)
VALUES ($1, $2, $3, $4, $5, ST_SetSRID(ST_MakePoint($6::float8, $7::float8), 4326)::geography, $8, $9, $10, $11)
RETURNING id, creator_id, title, description, category, location_name, 
          (ST_Y(location::geometry))::float8 AS latitude, 
          (ST_X(location::geometry))::float8 AS longitude, 
          start_time, end_time, max_participants, status, created_at
`

type CreateEventParams struct {
	CreatorID       int32              `json:"creator_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Category        string             `json:"category"`
	LocationName    string             `json:"location_name"`
	Column6         float64            `json:"column_6"`
	Column7         float64            `json:"column_7"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	MaxParticipants int32              `json:"max_participants"`
	Status          string             `json:"status"`
}

type CreateEventRow struct {
	ID              int32              `json:"id"`
	CreatorID       int32              `json:"creator_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Category        string             `json:"category"`
	LocationName    string             `json:"location_name"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	MaxParticipants int32              `json:"max_participants"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.CreatorID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.LocationName,
		arg.Column6,
		arg.Column7,
		arg.StartTime,
		arg.EndTime,
		arg.MaxParticipants,
		arg.Status,
	)
	var i CreateEventRow
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.MaxParticipants,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, creator_id, title, description, category, location_name,
       (ST_Y(location::geometry))::float8 AS latitude,
       (ST_X(location::geometry))::float8 AS longitude,
       start_time, end_time, max_participants, status, created_at
FROM events
WHERE id = $1 LIMIT 1
`

type GetEventByIDRow struct {
	ID              int32              `json:"id"`
	CreatorID       int32              `json:"creator_id"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Category        string             `json:"category"`
	LocationName    string             `json:"location_name"`
	Latitude        float64            `json:"latitude"`
	Longitude       float64            `json:"longitude"`
	StartTime       pgtype.Timestamptz `json:"start_time"`
	EndTime         pgtype.Timestamptz `json:"end_time"`
	MaxParticipants int32              `json:"max_participants"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEventByID(ctx context.Context, id int32) (GetEventByIDRow, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i GetEventByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatorID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.LocationName,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.MaxParticipants,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getNearbyEvents = `-- name: GetNearbyEvents :many
SELECT id, creator_id, title, description, category, location_name,
       (ST_Y(location::geometry))::float8 AS latitude,  -- Latitude
       (ST_X(location::geometry))::float8 AS longitude, -- Longitude
       ST_Distance(location, ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography)::float8 AS distance_meters
FROM events
WHERE status = 'active'
  AND ST_DWithin(location, ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography, $3::float8)
ORDER BY distance_meters ASC
LIMIT $4 OFFSET $5
`

type GetNearbyEventsParams struct {
	Column1 float64 `json:"column_1"`
	Column2 float64 `json:"column_2"`
	Column3 float64 `json:"column_3"`
	Limit   int32   `json:"limit"`
	Offset  int32   `json:"offset"`
}

type GetNearbyEventsRow struct {
	ID             int32   `json:"id"`
	CreatorID      int32   `json:"creator_id"`
	Title          string  `json:"title"`
	Description    string  `json:"description"`
	Category       string  `json:"category"`
	LocationName   string  `json:"location_name"`
	Latitude       float64 `json:"latitude"`
	Longitude      float64 `json:"longitude"`
	DistanceMeters float64 `json:"distance_meters"`
}

func (q *Queries) GetNearbyEvents(ctx context.Context, arg GetNearbyEventsParams) ([]GetNearbyEventsRow, error) {
	rows, err := q.db.Query(ctx, getNearbyEvents,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNearbyEventsRow
	for rows.Next() {
		var i GetNearbyEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatorID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.LocationName,
			&i.Latitude,
			&i.Longitude,
			&i.DistanceMeters,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEventStatus = `-- name: UpdateEventStatus :exec
UPDATE events
SET status = $2
WHERE id = $1
`

type UpdateEventStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) error {
	_, err := q.db.Exec(ctx, updateEventStatus, arg.ID, arg.Status)
	return err
}
