// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error)
	CreateUserAndProfile(ctx context.Context, arg CreateUserAndProfileParams) (CreateUserAndProfileRow, error)
	DeleteSession(ctx context.Context, refreshTokenHash string) error
	DeleteUserSessions(ctx context.Context, userID int32) error
	GetEventByID(ctx context.Context, id int32) (GetEventByIDRow, error)
	GetNearbyEvents(ctx context.Context, arg GetNearbyEventsParams) ([]GetNearbyEventsRow, error)
	GetSessionByHash(ctx context.Context, refreshTokenHash string) (UserSession, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error)
	UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) error
}

var _ Querier = (*Queries)(nil)
