// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (user_id, refresh_token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, refresh_token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	UserID           int32              `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshTokenHash, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM user_sessions
WHERE refresh_token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, refreshTokenHash string) error {
	_, err := q.db.Exec(ctx, deleteSession, refreshTokenHash)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM user_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByHash = `-- name: GetSessionByHash :one
SELECT id, user_id, refresh_token_hash, expires_at, created_at
FROM user_sessions
WHERE refresh_token_hash = $1 LIMIT 1
`

func (q *Queries) GetSessionByHash(ctx context.Context, refreshTokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getSessionByHash, refreshTokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
