// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAndProfile = `-- name: CreateUserAndProfile :one
WITH new_user AS (
    INSERT INTO users (email, password_hash)
    VALUES ($1, $2)
    RETURNING id
)
INSERT INTO profiles (user_id, username, full_name)
SELECT id, $3, $4 FROM new_user
RETURNING user_id, username, full_name
`

type CreateUserAndProfileParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Username     string `json:"username"`
	FullName     string `json:"full_name"`
}

type CreateUserAndProfileRow struct {
	UserID   int32  `json:"user_id"`
	Username string `json:"username"`
	FullName string `json:"full_name"`
}

func (q *Queries) CreateUserAndProfile(ctx context.Context, arg CreateUserAndProfileParams) (CreateUserAndProfileRow, error) {
	row := q.db.QueryRow(ctx, createUserAndProfile,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
		arg.FullName,
	)
	var i CreateUserAndProfileRow
	err := row.Scan(&i.UserID, &i.Username, &i.FullName)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT u.id, u.email, u.password_hash, p.username, p.full_name, p.avatar_url, p.bio, p.city
FROM users u
JOIN profiles p ON p.user_id = u.id
WHERE u.email = $1 LIMIT 1
`

type GetUserByEmailRow struct {
	ID           int32       `json:"id"`
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Username     string      `json:"username"`
	FullName     string      `json:"full_name"`
	AvatarUrl    pgtype.Text `json:"avatar_url"`
	Bio          pgtype.Text `json:"bio"`
	City         pgtype.Text `json:"city"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.City,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT u.id, u.email, p.username, p.full_name, p.avatar_url, p.bio, p.city
FROM users u
JOIN profiles p ON p.user_id = u.id
WHERE u.id = $1 LIMIT 1
`

type GetUserByIDRow struct {
	ID        int32       `json:"id"`
	Email     string      `json:"email"`
	Username  string      `json:"username"`
	FullName  string      `json:"full_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	Bio       pgtype.Text `json:"bio"`
	City      pgtype.Text `json:"city"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.Bio,
		&i.City,
	)
	return i, err
}
