ALTER TABLE events ADD COLUMN IF NOT EXISTS visibility VARCHAR(20) DEFAULT 'public';
ALTER TABLE events ADD COLUMN IF NOT EXISTS gender_filter VARCHAR(20) DEFAULT 'Все';
ALTER TABLE events ADD COLUMN IF NOT EXISTS min_age INT;
ALTER TABLE events ADD COLUMN IF NOT EXISTS max_age INT;
